services:

  backend:
    build: .
    container_name: otp-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: otp-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: